version: '3.8'

services:
  # Our PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: recon0_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: recon0_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: